### ISSUE TITLE
GIT_PR_RELEASE_BRANCH_PRODUCTION should accept empty string

### ISSUE THREAD

**Issue by pandanoir** [x-motemen/git-pr-release#83]
I usually use git-pr-release and like it!
However, git-pr-release requests consistent base branch(e.g. master or main). This behavior is not suitable for our use-case.

# Problem

We use git-pr-release in our project to create topic PR. Topic PR is directed to a "release" branch(not equal to main branch). Release branch is created every two weeks so GIT_PR_RELEASE_BRANCH_PRODUCTION cannot be consistent.

For more example, this step will show a problem to you.

1. Setup git-pr-release on a repository
2. Create release PR with git-pr-release
3. Change the base branch from main to another branch
4. Merge a PR to release PR
5. New release PR is created by git-pr-release instead of updating existing release PR

Could you make GIT_PR_RELEASE_BRANCH_PRODUCTION accept empty?

# Solution

To stop passing a base parameter when GIT_PR_RELEASE_BRANCH_PRODUCTION is empty will solve this problem.

https://github.com/x-motemen/git-pr-release/blob/a844d1bcb1b8747a813c3b6d9cb970eb8f8d9dfe/lib/git/pr/release/cli.rb#L168

**Comment by onk** [comment]
If you have a rule for branch names for releases every two weeks, you can set environment variables via some code.

```sh
$ GIT_PR_RELEASE_BRANCH_PRODUCTION=release_`date '+%Y%m%d'` git-pr-release
```

I think it's better than manually changing the base branch of the PR created by git-pr-release.

**Comment by pandanoir** [comment]
Thanks for fast response!

Sorry for my poor description. The base branch can be next release branch, prev release branch, main or even other branch. There is no stable rule.

So I want to specify only head branch to search for PR.

**Comment by pandanoir** [comment]
Is there any update?

**Comment by onk** [comment]
No updates.

git-pr-release is a library that creates and updates the differences between two branches as a "release PR".
If the PRODUCTION branch is set to empty, the release PR cannot be uniquely identified.  "base" and "head" branches are required to identify it.

I don't know what happens if can't identify the release PR.  (Probably randomly selected each time you run `git-pr-release`.)

And I don't know why you want to randamize the release PR.
If you need this feature, please explain the strategy (operation flow) of branches. (in Japanese OK

---

release PR を特定するために base/head を指定するのは必要なので、変更するつもりは今のところ無いですが、ブログにでも現状のブランチ戦略を書いてくれたら、そのブランチ戦略を採るメリット、git-pr-branch で対応するメリットに腹落ちできるかもしれません。

**Comment by pandanoir** [comment]
In short: I want a more general "release" PR that is the aggregate PR. Aggregate PR is not only release branch. For instance, when creating very large feature, we might want to split a PR into small PRs and mere them into "feature" branch.

If you don't want to deal with this, I've to create a plugin that is similar to git-pr-release but more general one and replace git-pr-release with it. I respect your opinion, so any answer is welcome!

However, I believe that generalize git-pr-release will help other people!

-----

(他の人も読むかもしれないので英語併記しました)

In short: リリースPRをより一般化した、他のPRのマージ先になるPR、を作れるようにして欲しいです。他のPRのマージ先になるPRはrelease PR以外にもあると思います。例えば大きい機能を作るとき、PRを細かく分けてレビューを行い、それをfeature PRにマージしていくユースケースはかなり一般的だと思います。

もし対応したくないとおっしゃるのでしたら、git-pr-releaseとほぼ同じ、feature PR にも対応したプラグインを自作して置き換えなければいけません。git-pr-releaseを参考に自作できると思う(当然外部に公開したりはしません)ので、どのような方針かだけお伺いしたいです。

ただ、git-pr-releaseをrelease PR以外にも対応させるのは他の人にも役に立つと思うので、一考をよろしくお願いします

**Comment by pandanoir** [comment]
面倒になったので日本語で書きますが、僕の方の疑問は、「なんで1つの release ブランチに対応する PR が2つ以上想定されているのか」に尽きます。

**Comment by mtgto** [comment]
Japanese below.

Hi, I'm a contributor of git-pr-release.
@pandanoir I read your comments, but I don't understand which pull requests you want to create (but it is difficult) by this tool.

To understand what you want to, I drew below git history example by [mermaid](https://mermaid-js.github.io/mermaid/#/gitgraph).
If there are mistakes in my comprehension, tell me it, please. 

### My comprehension

There are three branch types in your repo:

- `main` is base branch
- `release-YYYY-MM-DD` (a tmp name) is release branches
  - Checked out from `main` branch.
  - merge to main before release && check out new release branch
- `feature-XXX` is feature branches
  - Checked out from `main` branch
  - merge to next-candidated `release-YYYY-MM-DD` branch

You want to use git-pr-release: (Maybe 2-a or 2-b?)

1. to merge `feature-XXX` to next candidate release branch
2. to merge `release-YYYY-MM-DD` branch to `main` branch
  a. This pull request is created just before release (merge release branch to main)
  b. This pull request is created just after release branch is created && merge just before release

```mermaid
gitGraph
  commit
  commit
  branch release-2022-05-01
  checkout main
  branch release-2022-05-15
  checkout release-2022-05-01
  branch feature-A
  commit
  commit
  checkout release-2022-05-01
  merge feature-A
  checkout main
  branch feature-C
  commit
  commit
  checkout main
  branch feature-B
  commit
  commit
  checkout release-2022-05-01
  merge feature-B
  checkout main
  merge release-2022-05-01
  commit tag: "2022-05-01"
  checkout release-2022-05-15
  merge feature-C
  checkout main
  merge release-2022-05-15
  commit tag: "2022-05-15"
```

----
こんにちは。私はgit-pr-releaseのコントリビューターの一人です。
@pandanoir の書いたコメントを読みましたがどのPull Requestをgit-pr-releaseで作りたくてそれが今の仕組みではできなくて困っているのかよくわかりませんでした。
以下に私の理解を書きますので間違ってたら訂正をお願いします。上記のgit履歴のサンプルはmermaidを使って書いてみました。

### 私の理解

3種類のブランチの種類がある:

- ベースである `main`
- リリースブランチ `release-YYYY-MM-DD` (仮称)
  - `main`からcheckoutで作成される
  - リリース前に`main`にマージされ、新たなリリースブランチが作成される
- フィーチャーブランチ `feature-XXX`
  - `main`からcheckoutで作成される
  - 次のリリースブランチ `release-YYYY-MM-DD` にマージされる

あなたはgit-pr-releaseを次の目的で使いたい: (2-aか2-bでしょうか?)

1. `feature-XXX` を次のリリースブランチにマージするため
2. `release-YYYY-MM-DD` を `main` にマージするため
  a. このプルリクエストはリリース直前に作成する
  b. このリクエストは `release-YYYY-MM-DD` 作成直後に作成される

**Comment by pandanoir** [comment]
Yes, I want git-pr-release to achieve 1 and 2-b. git-pr-release can resolve case of 2-b now, but not case of 1.

はい、1と2-bの目的で使いたいです。2-bは現状でも達成できますが1が達成できません

**Comment by mtgto** [comment]
Thank you for reply.

> In short: I want a more general "release" PR that is the aggregate PR. Aggregate PR is not only release branch.

and

> Yes, I want git-pr-release to achieve 1 and 2-b. git-pr-release can resolve case of 2-b now, but not case of 1.

To do it (create pull request to merge feature branch) with git-pr-release, you can set env `GIT_PR_RELEASE_BRANCH_PRODUCTION` and `GIT_PR_RELEASE_BRANCH_STAGING` or `git config` or file `.git-pr-release`.

ex:

```console
GIT_PR_RELEASE_BRANCH_PRODUCTION=release-YYYY-MM-DD \
GIT_PR_RELEASE_BRANCH_STAGING=feature-XXX \
git-pr-release
```
(@onk said you can change branch name in first reply: https://github.com/x-motemen/git-pr-release/issues/83#issuecomment-1082042914 )

I agree with @onk https://github.com/x-motemen/git-pr-release/issues/83#issuecomment-1118250496 and I find it is difficult git-pr-release creates "more general release PR" because git-pr-release knows branch names neither feature-XXX nor release-YYYY-MM-DD until you set it.

If I were you, I would write a some wrapper script to set two branch names to env and run git-pr-release.
My script would do:

- If feature-XXX is current local branch name, set it to GIT_PR_RELEASE_BRANCH_STAGING
  - Another plans: pass it as argument
- `git branch --remote | grep origin/release` tells the name of release branch

I do not know what modifications to git-pr-release would make your suggestion feasible. Can you explain it?
----

返答ありがとうございます。

> In short: リリースPRをより一般化した、他のPRのマージ先になるPR、を作れるようにして欲しいです。

> はい、1と2-bの目的で使いたいです。2-bは現状でも達成できますが1が達成できません

もし1 (機能ブランチをリリースブランチにマージ) の達成のためにgit-pr-releaseを使いたいのであれば、環境変数`GIT_PR_RELEASE_BRANCH_PRODUCTION`と`GIT_PR_RELEASE_BRANCH_STAGING` (もしくは `git config` や ファイル `.git-pr-release`) を設定することで可能です。
(これは @onk が最初の返答 https://github.com/x-motemen/git-pr-release/issues/83#issuecomment-1082042914 でも触れていました)


私の意見も @onk の https://github.com/x-motemen/git-pr-release/issues/83#issuecomment-1118250496 と同じで、git-pr-release がpull requestのマージ元 (feature-XXX) とマージ先 (今回だとrelease-YYYY-MM-DD) がセットされないとPull Requestを作るために必要な情報がそろわないので無理そうです。

私があなたなら、git-pr-releaseにマージ元とマージ先を環境変数でセットしてから実行するラッパースクリプトを書けば解決するかなと思いました。

- マージ元ブランチ名はローカルリポジトリのブランチ名から取得する (もしくはスクリプトへの引数で指定する)
- マージ先ブランチ名はリモートリポジトリのブランチ名から取得する (`git branch --remote`の結果から)

私の理解ではgit-pr-releaseにどのような修正を行えばブランチ名を外から与えずに1を実現できるのかわかりませんでした。そこらへんになにか @pandanoir さんと私たちとの認識の違いがあるのかなと思っています。

**Comment by onk** [comment]
Thank you, @mtgto. In your work, the issue became clear.
And I'm excited about the commit graph drawn by Mermaid.js!


What @pandanoir want to do is

1. First, create a release PR from `feature-XXX` to `main`,
2. Then change the release PR's base branch to `release-YYYY-MM-DD`
3. Reuse the release PR

(like the steps to reproduce the PR description)

### You want to change the the base branch and reuse the release PR

- I understand your branch flow. Houever, it is recommended to use a wrapper script
- It seems difficult to write a workflow that specifies `main` for the first time, and an empty string for the second and subsequent times.
- Since it requires manual work, it would not be more useful.

### 「なんで1つの release ブランチに対応する PR が2つ以上想定されているのか」

* I see. I understand what you mean
* `git-pr-release` is a tool (often) used by "GitLab flow"
  - This flow uses eternal `main` and `production` branch. And merge `main` to `production` with each release
  - [Introduction to GitLab Flow | GitLab](https://docs.gitlab.com/ee/topics/gitlab_flow.html)

---

@mtgto ありがとうございます。論点が明確になって助かりました。
（Mermaid.js で Git のコミットグラフが描けるのを知ってすごく興奮しています！）

@pandanoir さんは、PR description の再現手順に書かれているように、一度 `main` に向けて PR を作ったあとに base branch を切り替えて release PR を再利用する、を実現したいのだと想像しています。

### main 向けの release PR を作った後に、base branch を付け替えて再利用したい

- 言っている意味は分かるんですが、wrapper script を用意するのをオススメします
- 初回は `main` を指定して、2 回目以降は空文字を指定するワークフローを書くのは難しそうなこと
- また、手作業が入っているので、このフローに対応してツールとしての有用性が増すことが無さそうなことが理由です

### 「なんで1つの release ブランチに対応する PR が2つ以上想定されているのか」

- release PR 用のブランチからは必ず 1 個しか PR が作られることは無い、というブランチ戦略もありそうですね。同意できます
- `git-pr-release` は GitLab flow で使われる (ことが多い) ツールだと思っています
  * これは `main` から `production` に向けて、リリースのたびにマージし続ける flow です
  * [Introduction to GitLab Flow | GitLab](https://docs.gitlab.com/ee/topics/gitlab_flow.html)

**Comment by pandanoir** [comment]
なるほど、理解できました。

僕のユースケースでは、まずmasterに向けたPRを作成します(ここではbaseの指定が必要)。次に、マージしたタイミングでPRのデスクリプションがgit-pr-releaseで更新されます**(ここではbaseを指定しなくてもいいはず)**。僕は作成のタイミングではmasterに向けておいて、あとで手動でreleaseに向きを直して、git-pr-releaseは更新の時はmasterに向いてるかを確認せずに実行してくれる動作を期待しています。

僕はずっと更新の時はbase要らないという話をしてて、onakaさんとmtgtoさんは作成の時はbaseが要るという話をしていたので噛み合っていなかったようです
